apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api
  labels:
    app: model-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
      - name: model-api
        image: matching_api_image
        imagePullPolicy: Never
        ports:
        - containerPort: 7777

---
apiVersion: v1
kind: Service
metadata:
  name: model-api-service
spec:
  type: NodePort
  selector:
    app: model-api
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 7777
      targetPort: 7777
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007